// This file is auto-generated by test_tstun_comprehensive.ts
    
export type TstunServerAddress = {
    url: string, 
    lastWorked?: Number,
    lastLatency?: Number, 
    tests?: Number, // how often it was tested
    failures?: Number // how often it failed
};

// run with:
// bash: (out of src1)
// npm run build && node ts-js-out/transport/test_tstun_comprehensive.js
// old ps: (out of src1)
// npm run build; node ts-js-out/transport/test_tstun_comprehensive.js

export const tstunServers: TstunServerAddress[] = [
  {
    "url": "stunt1.neurofleet.com:5000",
    "tests": 47,
    "lastWorked": 1746899982276,
    "lastLatency": 71
  },
  {
    "url": "stunt2.neurofleet.com:5001",
    "tests": 4,
    "lastWorked": 1746900003985,
    "lastLatency": 73
  },
  {
    "url": "stunt2.neurofleet.com:5002",
    "tests": 4,
    "lastWorked": 1746899986646,
    "lastLatency": 77
  }
]